from comandos.clear import setup_clear
from comandos.random import setup_random
from comandos.moverinf import setup_moverinf
from comandos.avatar import setup_avatar
from comandos.status import setup_status
from comandos.password import setup_password
from comandos.joke import setup_joke
from comandos.to_binary import setup_to_binary
from comandos.from_binary import setup_from_binary
from comandos.define import setup_define
from comandos.hash import setup_hash
from comandos.shuffle import setup_shuffle
from comandos.calc import setup_calc
from comandos.encrypt import setup_encrypt
from comandos.say import setup_say
from comandos.gift import setup_gift
from comandos.ipinfo import setup_ipinfo
from comandos.embed import setup_embed
from comandos.dm import setup_dm
from comandos.banir import setup_banir
from comandos.expulsar import setup_expulsar
from comandos.serverinfo import setup_serverinfo
from comandos.wiki import setup_wiki
from comandos.info_user import setup_info_user
from comandos.role_info import setup_role_info
from comandos.delete_webhook import setup_delete_webhook
from comandos.channel_info import setup_channel_info
from comandos.help.help import setup_help
from comandos.help.add_command import setup_add_command
from comandos.txt import setup_txt
from comandos.imagine import setup_imagine
from comandos.lock import setup_lock
from comandos.cep import setup_cep
from comandos.cnpj import setup_cnpj
from comandos.qr import setup_qr
from comandos.gen import setup_gen
from comandos.raid import setup_raid
from comandos.get_html import setup_get_html
from comandos.invite import setup_invite
from comandos.get_buttons import setup_get_buttons
from comandos.tokeninfo import setup_tokeninfo
from comandos.get_links import setup_get_links
from comandos.clone import setup_clone
from comandos.extrair import setup_extrair
from comandos.dowload import setup_dowload
from comandos.addemoji import setup_addemoji
from comandos.slowmode import setup_slowmode
from comandos.poder import setup_poder
from comandos.count import setup_count
from comandos.randomname import setup_randomname
from comandos.coinflip import setup_coinflip
from comandos.listwebhooks import setup_listwebhooks
from comandos.colorinfo import setup_colorinfo
from comandos.geniptv import setup_geniptv
from comandos.CPF import setup_cpf
from comandos.qrscan import setup_qrscan
from comandos.psicologo import setup_psicologo
from comandos.gerarcodigos import setup_gerarcodigos
from comandos.sync import setup_sync
from comandos.castigar import setup_castigar
from comandos.parar import setup_desligar
from comandos.callprivada import setup_call
from comandos.fake import setup_fake
from comandos.ticket import setup_ticket
from comandos.nuke import setup_nuke